### ISSUE TITLE
IOError: [Errno 2] No such file or directory: 'README.md'

### ISSUE THREAD

**Issue by cancan101** [AllenDowney/ThinkX#3]
```
$ pip install thinkx
Collecting thinkx
  Downloading thinkx-1.0.tar.gz (54kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-z0mYjJ/thinkx/setup.py", line 13, in <module>
        long_description=readme(),
      File "/tmp/pip-build-z0mYjJ/thinkx/setup.py", line 5, in readme
        with open('README.md') as f:
    IOError: [Errno 2] No such file or directory: 'README.md'
```

**Comment by AllenDowney** [comment]
I just pushed an update to PyPI that should fix this.  Let me know how it goes!
